CREATE TABLE `USUARIO` (
  `IDUSUARIO` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) NOT NULL,
  `LOGIN` varchar(40) NOT NULL,
  `SENHA` varchar(100) NOT NULL,
  `SETOR` varchar(100) NOT NULL,
  PRIMARY KEY (`IDUSUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;


CREATE TABLE `organization` (
  `idorganization` integer NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `status` bool NOT NULL,
  `tags` text NOT NULL,
  `accesskey` varchar(100) NOT NULL
)ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8;
